# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(296, 379)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_file_btn = QtWidgets.QPushButton(self.centralwidget)
        self.input_file_btn.setObjectName("input_file_btn")
        self.gridLayout_2.addWidget(self.input_file_btn, 0, 0, 1, 1)
        self.output_file_btn = QtWidgets.QPushButton(self.centralwidget)
        self.output_file_btn.setObjectName("output_file_btn")
        self.gridLayout_2.addWidget(self.output_file_btn, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.console_plain_text_edit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.console_plain_text_edit.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(56, 12, 42);")
        self.console_plain_text_edit.setObjectName("console_plain_text_edit")
        self.console_plain_text_edit.setReadOnly(True)
        self.console_plain_text_edit.setCursor(Qt.ArrowCursor) 
        self.console_plain_text_edit.viewport().setCursor(Qt.ArrowCursor) 
        self.verticalLayout.addWidget(self.console_plain_text_edit)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.version_lbl = QtWidgets.QLabel(self.centralwidget)
        self.version_lbl.setObjectName("version_lbl")
        self.gridLayout_3.addWidget(self.version_lbl, 0, 0, 1, 1)
        self.run_btn = QtWidgets.QPushButton(self.centralwidget)
        self.run_btn.setStyleSheet("background-color: rgb(51, 209, 122);")
        self.run_btn.setObjectName("run_btn")
        self.gridLayout_3.addWidget(self.run_btn, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 296, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CMScrape 2"))
        self.input_file_btn.setText(_translate("MainWindow", "Input File"))
        self.output_file_btn.setText(_translate("MainWindow", "Output File"))
        self.version_lbl.setText(_translate("MainWindow", "v0.01"))
        self.run_btn.setText(_translate("MainWindow", "Run"))
